### ISSUE TITLE
Linear regression bias clarification

### ISSUE THREAD

**Issue by joelgenter** [bfortuner/ml-cheatsheet#54]
I just want to clarify my understanding before making any clarifying changes. In the Linear Regression article under 'Bias Term', it reads: 

> Below we add a constant 1 to our features matrix. By setting this value to 1, it turns our bias term into a constant.
>
> bias = np.ones(shape=(len(features),1))
> features = np.append(bias, features, axis=1)

So the purpose of adding the 1 along with the other features in each example is so that the 1 will be multiplied by the 'bias weight' when the dot product of the features and weights is performed in the predict() function. Is that accurate?

**Comment by bfortuner** [comment]
I think the bias is added not multiplied, right?

**Comment by ivanistheone** [comment]
> So the purpose of adding the 1 along with the other features in each example is so that the 1 will be multiplied by the 'bias weight' when the dot product of the features and weights is performed in the predict() function. Is that accurate? 

Yes, exactly. We "augement" the data with a column of constant 1 so that can treeat the whole expressions using dot product rather than handle bias manually. Here is an example shows its equivalent:

<img width="589" alt="screen shot 2019-02-14 at 8 33 04 am" src="https://user-images.githubusercontent.com/163966/52790050-89826400-3033-11e9-94ce-266b464f2b7a.png">

**Comment by joelgenter** [comment]
Awesome. Thank you!
